config/routes.rb
Rails.application.routes.draw do
  get "/", to: "flats#index", as: :flats
  # /flats/145 -> flat["id"] = 145
  get "/flats/:id", to: "flats#show", as: :flat
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController

  def index
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end

  def show
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
    @id = params[:id].to_i


    @flat = @flats.select {|flat| flat["id"] == @id }.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats#index</h1>
<p>Find me in app/views/flats/index.html.erb</p>
<% @flats.each do |flat| %>
  <p><%= flat["price"] %> - <%= flat["priceCurrency"]%></p>
  <!-- link to the show page -->
  <%= link_to flat["name"], flat_path(flat["id"]) %>
  <%= link_to flat_path(flat["id"]) do %>
    <img src="<%= flat["imageUrl"] %>" width="200">
  <% end %>
<% end %>
<!-- link_to "anchor text", path -->

app/views/flats/show.html.erb
<h1>More about <%= @flat["name"] %></h1>
<p>Price: <%= @flat["price"]  %> <%= @flat["priceCurrency"] %></p>
<!-- link_to "Anchor button", prefix_path -->
<%= link_to "Back",  flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>